name: "Changed Files"
on:
  push:
    branches: [ master, '[0-9]*' ]
  pull_request_target:
  # Allows triggering the job manually
  workflow_dispatch:

env:
  EXCLUDE_FOLDERS: ".github,.buildkite"

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: "Install dependencies"
        run: python -m pip install .[develop]
      - name: Dynamically parse tracks
        run: |
          python3 <<EOF
          import os, yaml
          exclude = set(os.environ.get('EXCLUDE_FOLDERS', '').split(','))
          filters = {}
          for entry in os.listdir('.'):
              if os.path.isdir(entry) and entry not in exclude:
                  filters[entry] = [f"{entry}/**"]
          with open('.github/filters.yml', 'w') as f:
              yaml.dump(filters, f, default_flow_style=False)
          EOF
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/filters.yml
      - name: Build track filter list
        id: track_filter
        run: |
          TRACKS=$(python3 .github/get_tracks.py .github/filters.yml)
          echo "tracks=$TRACKS" >> $GITHUB_OUTPUT

      - name: "Run tests"
        run: hatch -v -e it run test --track-filter=${{ steps.track_filter.outputs.tracks }}
