name: "Changed Files"
on:
  push:
    branches: [ master, '[0-9]*' ]
  pull_request_target:
  # Allows triggering the job manually
  workflow_dispatch:

env:
  EXCLUDE_FOLDERS: ".github,.buildkite"

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: "Install dependencies"
        run: python -m pip install .[develop]
      - name: Parse repo and create filters.yml
        run: python3 .github/scripts/track-filter.py
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/filters.yml
      - name: Collect changed tracks for --track-filter argument
        id: track_filter
        run: |
          for output in ${{ toJSON(steps.changes.outputs) }}
          do
            if [ "$output" = "true" ]; then
              TRACKS="$TRACKS,$track"
            fi
          done
          TRACKS="${TRACKS#,}"  # Remove leading comma
          echo "tracks=$TRACKS" >> $GITHUB_OUTPUT
      - name: "Run tests for tracks: ${{ steps.track_filter.outputs.tracks }}"
        run: hatch -v -e it run test --track-filter="${{ steps.track_filter.outputs.tracks }}"
